groups/urls.py
from django.urls import path

from groups.views import GroupListView, GroupCreateView, GroupUpdateView, GroupDetailView, GroupDeleteView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', GroupDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', GroupDeleteView.as_view(), name='delete'),
    ]

lms/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

    # path('test/route/param/', view_without_param),          # test/route/param/
    # path(r'test/route/<str:value>/', view_with_param),       # test/route/df;lkjhrlkjgf's/
]

groups/models.py
from django.db import models
from faker import Faker

from teachers.models import Teacher
from .validators import validate_start_date


class Group(models.Model):
    title = models.CharField(max_length=50)
    start_date = models.DateField(validators=[validate_start_date])
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    headman = models.OneToOneField('students.Student', on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='headman_group')
    teachers = models.ManyToManyField(to=Teacher, blank=True, related_name='groups')
    course = models.OneToOneField('courses.Course', on_delete=models.SET_NULL, null=True, blank=True,
                                  related_name='group')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'groups'

    @classmethod
    def generate_data(cls):
        faker = Faker()
        for title in 'Python', 'C1/C++', 'C#', 'Ruby', 'Java', 'JavaScript', 'Assembler', 'HTML+CSS':
            group = cls()
            group.title = title
            group.start_date = faker.date_between(start_date='+0y', end_date='+5y')
            group.description = faker.text()
            group.save()

    def __str__(self):
        return f'Group: {self.title}'

groups/forms.py
from django import forms

from students.models import Student
from .models import Group


class GroupBaseForm(forms.ModelForm):
    students = forms.ModelMultipleChoiceField(queryset=None, required=False)

    # def save(self, commit=True):
    #     new_group = super().save(commit)
    #     students = self.cleaned_data['students']
    #     for student in students:
    #         student.group = new_group
    #         student.save()

    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }


class GroupCreateForm(GroupBaseForm):
    # students = forms.ModelMultipleChoiceField(queryset=Student.objects.filter(group__isnull=True))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['students'].queryset = Student.objects.filter(group__isnull=True).select_related('group')

    class Meta(GroupBaseForm.Meta):
        exclude = [
            'headman',
        ]


class GroupUpdateForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['students'].queryset = Student.objects.filter(group__isnull=True).select_related('group')
        self.fields['headman_field'] = forms.ChoiceField(
            choices=[(st.pk, f'{st.first_name} {st.last_name}') for st in self.instance.students.all()],
            label='Headman',
            required=False,
        )
        self.fields['headman_field'].choices.insert(0, (0, '------'))

    class Meta(GroupBaseForm.Meta):
        exclude = [
            'start_date',
            'headman'
        ]

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from students.models import Student
from .forms import GroupCreateForm, GroupUpdateForm
from .models import Group


class GroupListView(ListView):
    model = Group
    template_name = 'groups/list.html'


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups/create.html'
    success_url = reverse_lazy('groups:list')

    def form_valid(self, form):
        response = super().form_valid(form)

        new_groups = form.save()

        students = form.cleaned_data['students']
        for student in students:
            student.group = new_groups
            student.save()

        return response


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupUpdateForm
    template_name = 'groups/update.html'
    success_url = reverse_lazy('groups:list')

    def get_initial(self):
        initial = super().get_initial()
        try:
            initial['headman_field'] = self.object.headman.pk
        except AttributeError:
            pass

        return initial

    def form_valid(self, form):
        response = super().form_valid(form)

        students = form.cleaned_data['students']
        for student in students:
            student.group = self.object
            if hasattr(student, 'headman_group'):
                group = student.headman_group
                group.headman = None
                group.save()
            student.save()

        headman_pk = int(form.cleaned_data.get('headman_field'))
        if headman_pk:
            form.instance.headman = Student.objects.get(pk=headman_pk)
        else:
            form.instance.headman = None
        form.save()

        return response


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'groups/detail.html'


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = 'groups/delete.html'
    success_url = reverse_lazy('groups:list')

groups/templates/groups/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new group{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Create">
                    <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

groups/templates/groups/delete.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Delete selected Group{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="text-center">
                    <p>Do you really want to delete group <strong>{{ group.title }}</strong>?</p>
                    <input class="btn btn-outline-primary" type="submit" value="Agree">
                    <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

groups/templates/groups/detail.html
{% extends 'base.html' %}

{% block title %}Details of selected Group{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col align-self-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Title: {{ group.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Start date: {{ group.start_date|date:"d M Y" }}</h6>
                    <p class="card-text">{{ group.description }}</p>
                    <a class="btn btn-outline-primary" href="{% url 'groups:update' group.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Back to list</a>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

groups/templates/groups/list.html
{% extends 'base.html' %}

{% block title %}List of Groups{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th></th>
                        <th>Title</th>
                        <th>Course</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Headman</th>
                        {% if user.is_authenticated %}
                            <th><i class="bi bi-pencil-fill"></i></th>
                            <th><i class="bi bi-person-x-fill"></i></th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for group in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if user.is_authenticated %}
                                <td><a href="{% url 'groups:detail' group.pk %}">{{ group.title }}</a></td>
                            {% else %}
                                <td>{{ group.title }}</td>
                            {% endif %}
                            <td class="text-center">{% if group.course %}{{ group.course }}{% endif %}</td>
                            <td class="text-center">{{ group.start_date|date:"d M Y" }}</td>
                            <td class="text-center">{{ group.end_date|date:"d M Y" }}</td>
                            <td class="text-center">{% if group.headman %}{{ group.headman.first_name }}{{ group.headman.last_name }}{% endif %}</td>
                            {% if user.is_authenticated %}
                                <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'groups:update' group.pk %}">Edit</a> </td>
                                <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'groups:delete' group.pk %}">Remove</a> </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

groups/templates/groups/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update selected group{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Update">
                    <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row">
        {% with object_list=group.students.all is_group=True %}
            {% include 'includes/students_table.html' %}
        {% endwith %}
    </div>
{% endblock %}