lms/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

    # path('test/route/param/', view_without_param),          # test/route/param/
    # path(r'test/route/<str:value>/', view_with_param),       # test/route/df;lkjhrlkjgf's/
]

teachers/urls.py
from django.urls import path

from .views import TeacherListView, TeacherCreateView, TeacherUpdateView, TeacherDetailView, TeacherDeleteView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', TeacherDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', TeacherDeleteView.as_view(), name='delete')
    ]

teachers/models.py
import datetime
from decimal import Decimal
from random import randint

from dateutil.relativedelta import relativedelta
from django.db import models
from faker import Faker

from core.models import PersonModel


class Teacher(PersonModel):
    salary = models.PositiveIntegerField(default=10_000)

    class Meta(PersonModel.Meta):
        db_table = 'teachers'

    def __str__(self):
        return f'{self.first_name} {self.last_name} (${self.salary})'

    def __repr__(self):
        return f'<Teacher({self.first_name} {self.last_name})>'

    @classmethod
    def _generate(cls):
        teacher = super()._generate()
        teacher.salary = randint(10_000, 100_000)
        return teacher

teachers/forms.py
from django import forms

from .models import Teacher


class CreateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name',
                  'last_name',
                  'birthday',
                  'salary',
                  'email',
                  ]
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }


class UpdateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name',
                  'last_name',
                  'birthday',
                  'salary',
                  'email',
                  ]
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from .forms import CreateTeacherForm
from .forms import UpdateTeacherForm
from .models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers/list.html'


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = CreateTeacherForm
    template_name = 'teachers/create.html'
    success_url = reverse_lazy('teachers:list')


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = UpdateTeacherForm
    template_name = 'teachers/create.html'
    success_url = reverse_lazy('update:list')


class TeacherDetailView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = 'teachers/detail.html'


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = 'teachers/delete.html'
    success_url = reverse_lazy('teachers:list')

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new Teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-outline-primary" type="submit" value="Create">
                <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}Delete selected Teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="text-center">
                    <p>Do you really want to delete teacher <strong>{{ teacher.first_name }} {{ teacher.last_name }}</strong>?</p>

                    <input class="btn btn-outline-primary" type="submit" value="Agree">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

teachers/templates/teachers/detail.html
{% extends 'base.html' %}

{% block title %}Details of selected Teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col align-self-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ teacher.email }}</h6>
                    <p class="card-text">Birthday: {{ teacher.birthday|date:"d M Y" }} ({{ teacher.get_age }} year(s))</p>
                    <p class="card-text">Salary: {{ teacher.salary }}</p>
                    <a class="btn btn-outline-primary" href="{% url 'teachers:update' teacher.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% block title %}List of teachers{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th></th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Birthday</th>
                        {% if user.is_authenticated %}
                            <th><i class="bi bi-pencil-fill"></i></th>
                            <th><i class="bi bi-person-x-fill"></i></th>
                        {% endif %}
                    </tr>
                <thead>
                <tbody>
                    {% for teacher in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if user.is_authenticated %}
                                <td><a href="{% url 'teachers:detail' teacher.pk %}">{{ teacher.first_name }}</a></td>
                            {% else %}
                                <td>{{ teacher.first_name }}</td>
                            {% endif %}
                            <td>{{ teacher.last_name }}</td>
                            <td class="text-center">{{ teacher.birthday|date:"d M Y" }}</td>
                            {% if user.is_authenticated %}
                                <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'teachers:update' teacher.pk %}">Edit</a></td>
                                <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'teachers:delete' teacher.pk %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update selected Teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-outline-primary" type="submit" value="Update">
                <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}