courses/urls.py
from django.urls import path

from courses.views import CourseListView, CourseCreateView, CourseUpdateView, CourseDetailView, CourseDeleteView

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='delete'),
    ]

lms/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', index, name='home'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

    # path('test/route/param/', view_without_param),          # test/route/param/
    # path(r'test/route/<str:value>/', view_with_param),       # test/route/df;lkjhrlkjgf's/
]

courses/models.py
from django.db import models
from faker import Faker

from core.models import BaseModel


class Course(BaseModel):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    lesson_count = models.IntegerField(default=12, blank=True, null=True)

    class Meta(BaseModel.Meta):
        db_table = 'courses'

    def __str__(self):
        return self.title

    @classmethod
    def generate_data(cls, cnt):
        faker = Faker()
        for title in 'PythonPro', "Learning not to write shit's code", 'Django', 'Game development':
            obj = cls(title=title,
                      description=faker.text(),
                      lesson_count=faker.pyint(min_value=12, max_value=36, step=4))
            obj.save()

courses/forms.py
from django import forms

from courses.models import Course


class CourseBaseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class CourseCreateForm(CourseBaseForm):
    class Meta(CourseBaseForm.Meta):
        pass


class CourseUpdateForm(CourseBaseForm):
    class Meta(CourseBaseForm.Meta):
        pass

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from courses.forms import CourseCreateForm, CourseUpdateForm
from courses.models import Course


class CourseListView(ListView):
    model = Course
    template_name = 'courses/list.html'


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/create.html'


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = CourseUpdateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/update.html'


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/detail.html'


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/delete.html'

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Create">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Delete selected Course{% endblock %}

{% block content %}
<!--    <div class="row">-->
<!--        <div class="col-3"></div>-->
<!--        <div class="col">-->
<!--            <form method="post">-->
<!--                {% csrf_token %}-->
<!--                <div class="text-center">-->
<!--                    <p>Do you really want to delete course <strong>{{ course.title }}</strong>?</p>-->
<!--                    <input class="btn btn-outline-primary" type="submit" value="Agree">-->
<!--                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>-->
<!--                </div>-->
<!--            </form>-->
<!--        </div>-->
<!--        <div class="col-3"></div>-->
<!--    </div>-->
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="text-center">
                    <p>Do you really want to delete course <strong>{{ course.title }}</strong>?</p>

                    <input class="btn btn-outline-primary" type="submit" value="Agree">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/detail.html
{% extends 'base.html' %}

{% block title %}Details of selected course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col align-self-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Title: {{ course.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Lessons: {{ course.lesson_count }}</h6>
                    <p class="card-text">{{ course.description }}</p>
                    <a class="btn btn-outline-primary" href="{% url 'courses:update' course.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% block title %}List of Courses{% endblock %}

{% block content %}
<div class="row">
        <div class="col-3"></div>
        <div class="col">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th></th>
                        <th>Title</th>
                        <th>Lessons</th>
                        {% if user.is_authenticated %}
                            <th><i class="bi bi-pencil-fill"></i></th>
                            <th><i class="bi bi-person-x-fill"></i></th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for course in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if user.is_authenticated %}
                                <td><a href="{% url 'courses:detail' course.pk %}">{{ course.title }}</a></td>
                            {% else %}
                                <td>{{ course.title }}</td>
                            {% endif %}
                            <td class="text-center">{{ course.lesson_count }}</td>
                            {% if user.is_authenticated %}
                                <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'courses:update' course.pk %}">Edit</a> </td>
                                <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'courses:delete' course.pk %}">Remove</a> </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create selected course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Update">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}